default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: custom_fields_development

test:
  <<: *default
  database: custom_fields_test

production:
  <<: *default
  database: custom_fields_production
  username: custom_fields
  password: <%= ENV['CUSTOM_FIELDS_DATABASE_PASSWORD'] %>
